security:
    encoders:
        HR\Bundle\UserBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: user.user_provider

    acl: ~

    firewalls:
        main:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
            remember_me:
                key: %secret%
                lifetime: 31536000
                path: /
                domain: ~
                always_remember_me: true
            logout:
                path:   logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }