security:
    encoders:
        HR\UserBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        hr_userbundle:
            id: user.user_provider

    acl: ~

    firewalls:
        main:
            pattern:    ^/
            form_login:
                provider: hr_userbundle
                login_path: /login
                check_path: /login_check
            remember_me:
                key: %secret%
                lifetime: 31536000
                path: /
                domain: ~
                always_remember_me: true
            logout: ~
            anonymous: ~

            oauth:
                resource_owners:
                    weibo:         /login/check-weibo
                login_path:        /login
                failure_path:      /connect/check

                oauth_user_provider:
                    service:       user.oauth_provider

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }